load_data:
  download_data:
    path: data/data.csv
  upload_data:
    input_path: data/data.csv
    bucket_name: nw-skyesheng-s3
    output_path: 423project/data.csv
  load_csv:
    path: data/data.csv
preprocess_data:
  generate_class:
    target: type
    response1: I-E
    response2: N-S
    response3: T-F
    response4: J-P
generate_feature:
  add_feature:
    path: data/class_data.csv
    target: posts
    f1: words_per_comment
    f2: http_per_comment
    f3: music_per_comment
    f4: question_per_comment
    f5: img_per_comment
    f6: excl_per_comment
    f7: ellipsis_per_comment
train_model:
  split_data:
    path: data/model_data.csv
    features: ['words_per_comment','http_per_comment','music_per_comment','question_per_comment','img_per_comment','excl_per_comment','ellipsis_per_comment']
    targets: ['I-E','N-S','T-F','J-P']
    test_size: 0.4
    random_state: 1
  train:
    method: logistic_regression
evaluate_model:
  evaluate_model:
    xtestpath: data/xtest.csv
  post_process:
    features: ['words_per_comment','http_per_comment','music_per_comment','question_per_comment','img_per_comment','excl_per_comment','ellipsis_per_comment']





